<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Homecounty;
use App\Models\Constituency;
use App\Models\Subcounty;

class HomecountySeeder extends Seeder
{
    public function run()
    {
        $counties = [
            'Mombasa' => [
                'Changamwe' => ['Port Reitz', 'Airport'],
                'Jomvu' => ['Miritini', 'Mikindani'],
                'Kisauni' => ['Bamburi', 'Mshomoroni', 'Junda'],
                'Nyali' => ['Kongowea', 'Frere Town'],
                'Likoni' => ['Likoni', 'Mtongwe'],
                'Mvita' => ['Majengo', 'Tudor', 'Ganjoni'],
            ],
            'Kwale' => [
                'Msambweni' => ['Kinondo', 'Gombato'],
                'Lunga Lunga' => ['Vanga', 'Dzombo'],
                'Matuga' => ['Kwale Town', 'Tiwi'],
                'Kinango' => ['Mackinnon', 'Puma'],
            ],
            'Kilifi' => [
                'Kilifi North' => ['Tezo', 'Kibarani'],
                'Kilifi South' => ['Mtwapa', 'Shimo la Tewa'],
                'Kaloleni' => ['Kaloleni', 'Mariakani'],
                'Rabai' => ['Rabai', 'Kambe'],
                'Ganze' => ['Ganze', 'Bamba'],
                'Malindi' => ['Malindi Town', 'Ganda'],
                'Magarini' => ['Magarini', 'Gongoni'],
            ],
            'Tana River' => [
                'Garsen' => ['Garsen', 'Kipini'],
                'Galole' => ['Hola', 'Chewani'],
                'Bura' => ['Madogo', 'Bura'],
            ],
            'Lamu' => [
                'Lamu East' => ['Faza', 'Kiunga'],
                'Lamu West' => ['Mpeketoni', 'Witu'],
            ],
            'Taita Taveta' => [
                'Taveta' => ['Taveta', 'Chala'],
                'Wundanyi' => ['Wundanyi', 'Mbale'],
                'Mwatate' => ['Mwatate', 'Bura'],
                'Voi' => ['Voi', 'Sagala'],
            ],
            'Garissa' => [
                'Garissa Township' => ['Central', 'Iftin'],
                'Balambala' => ['Balambala', 'Danyere'],
                'Lagdera' => ['Modogashe', 'Baraki'],
                'Dadaab' => ['Dadaab', 'Liboi'],
                'Fafi' => ['Bura', 'Nanighi'],
                'Ijara' => ['Ijara', 'Masalani'],
            ],
            'Wajir' => [
                'Wajir North' => ['Bute', 'Gurar'],
                'Wajir East' => ['Wajir Town', 'Khorof Harar'],
                'Tarbaj' => ['Tarbaj', 'Elben'],
                'Wajir West' => ['Griftu', 'Habaswein'],
                'Eldas' => ['Eldas', 'Della'],
                'Wajir South' => ['Habaswein', 'Buna'],
            ],
            'Mandera' => [
                'Mandera West' => ['Takaba', 'Lagsure'],
                'Banissa' => ['Banissa', 'Derkale'],
                'Mandera North' => ['Rhamu', 'Rhamu Dimtu'],
                'Mandera South' => ['Elwak', 'Kutulo'],
                'Mandera East' => ['Mandera Town', 'Neboi'],
                'Lafey' => ['Lafey', 'Wargadud'],
            ],
            'Marsabit' => [
                'Moyale' => ['Butiye', 'Uran'],
                'North Horr' => ['North Horr', 'Dukana'],
                'Saku' => ['Marsabit Town', 'Sagante'],
                'Laisamis' => ['Laisamis', 'Logologo'],
            ],
            'Isiolo' => [
                'Isiolo North' => ['Wabera', 'Bulapesa'],
                'Isiolo South' => ['Garbatulla', 'Kinna'],
            ],
            'Meru' => [
                'Igembe South' => ['Kiegoi', 'Athiru Ruujine'],
                'Igembe Central' => ['Kangeta', 'Athiru Gaiti'],
                'Igembe North' => ['Maua', 'Laare'],
                'Tigania West' => ['Mikinduri', 'Thangatha'],
                'Tigania East' => ['Muthara', 'Karama'],
                'North Imenti' => ['Municipality', 'Nyaki West'],
                'Buuri' => ['Timau', 'Kiirua Naari'],
                'Central Imenti' => ['Kibirichia', 'Abothuguchi Central'],
                'South Imenti' => ['Abogeta West', 'Nkuene'],
            ],
            'Tharaka-Nithi' => [
                'Maara' => ['Muthambi', 'Chogoria'],
                'Chuka/Igambang\'ombe' => ['Chuka', 'Igambang\'ombe'],
                'Tharaka' => ['Tharaka South', 'Tharaka North'],
            ],
            'Embu' => [
                'Manyatta' => ['Kithimu', 'Nginda'],
                'Runyenjes' => ['Runyenjes Town', 'Kyeni North'],
                'Mbeere South' => ['Mavuria', 'Makima'],
                'Mbeere North' => ['Ngiiri', 'Muminji'],
            ],
            'Kitui' => [
                'Mwingi North' => ['Kyuso', 'Ngomeni'],
                'Mwingi West' => ['Mwingi Town', 'Kiomo/Kyethani'],
                'Mwingi Central' => ['Waita', 'Nguni'],
                'Kitui West' => ['Mutonguni', 'Kauwi'],
                'Kitui Rural' => ['Kisasi', 'Yatta/Kwa Vonza'],
                'Kitui Central' => ['Miambani', 'Township'],
                'Kitui East' => ['Nzambani', 'Zombe/Mwitika'],
                'Kitui South' => ['Mutomo', 'Ikanga/Kyatune'],
            ],
            'Machakos' => [
                'Masinga' => ['Kivaa', 'Muthesya'],
                'Yatta' => ['Katangi', 'Kithimani'],
                'Kangundo' => ['Kangundo Town', 'Matungulu North'],
                'Matungulu' => ['Matungulu East', 'Kyeleni'],
                'Kathiani' => ['Mitaboni', 'Kathiani Town'],
                'Mavoko' => ['Athi River', 'Kinanie'],
                'Machakos Town' => ['Mutituni', 'Mumbuni North'],
                'Mwala' => ['Masii', 'Mbiuni'],
            ],
            'Makueni' => [
                'Mbooni' => ['Tulimani', 'Mbooni Town'],
                'Kilome' => ['Kasikeu', 'Mukaa'],
                'Kaiti' => ['Ukia', 'Kilungu'],
                'Makueni' => ['Wote', 'Mavindini'],
                'Kibwezi West' => ['Makindu', 'Nguumo'],
                'Kibwezi East' => ['Mtito Andei', 'Masongaleni'],
            ],
            'Nyandarua' => [
                'Kinangop' => ['Engineer', 'Njabini/Kiburu'],
                'Kipipiri' => ['Geta', 'Kipipiri'],
                'Ol Kalou' => ['Kaimbaga', 'Karau'],
                'Ol Jorok' => ['Gathanji', 'Ol Jorok'],
                'Ndaragwa' => ['Central', 'Leshau Pondo'],
            ],
            'Nyeri' => [
                'Tetu' => ['Tetu', 'Wamagana'],
                'Kieni' => ['Naromoru/Kiamathaga', 'Mwiyogo/Endarasha'],
                'Mathira' => ['Konyu', 'Magutu'],
                'Othaya' => ['Mahiga', 'Iria-Ini'],
                'Mukurweini' => ['Gikondi', 'Mukurweini West'],
                'Nyeri Town' => ['Kamakwa/Mukaro', 'Ruringu'],
            ],
            'Kirinyaga' => [
                'Mwea' => ['Wachoro', 'Mutithi'],
                'Gichugu' => ['Kabare', 'Njukiini'],
                'Ndia' => ['Mukure', 'Kariti'],
                'Kirinyaga Central' => ['Kerugoya/Kutus', 'Inoi'],
            ],
            'Murang\'a' => [
                'Kangema' => ['Muguru', 'Rwathia'],
                'Mathioya' => ['Gitugi', 'Kiru'],
                'Kiharu' => ['Wangu', 'Murarandia'],
                'Kigumo' => ['Kigumo', 'Muthithi'],
                'Maragwa' => ['Makuyu', 'Kambiti'],
                'Kandara' => ['Gaichanjiru', 'Muruka'],
                'Gatanga' => ['Kariara', 'Kakuzi/Mitubiri'],
            ],
            'Kiambu' => [
                'Gatundu South' => ['Kiamwangi', 'Kiamwangi'],
                'Gatundu North' => ['Gituamba', 'Githobokoni'],
                'Juja' => ['Witeithie', 'Murera'],
                'Thika Town' => ['Hospital', 'Township'],
                'Ruiru' => ['Biashara', 'Gatongora'],
                'Githunguri' => ['Ikinu', 'Githunguri'],
                'Kiambu' => ['Ndumberi', 'Ting\'ang\'a'],
                'Kiambaa' => ['Cianda', 'Karuri'],
                'Kabete' => ['Kabete', 'Nyadhuna'],
                'Kikuyu' => ['Kikuyu', 'Sigona'],
                'Limuru' => ['Limuru Town', 'Ndeiya'],
                'Lari' => ['Kinale', 'Kamburu'],
            ],
            'Turkana' => [
                'Turkana North' => ['Kaikor', 'Lapur'],
                'Turkana West' => ['Kakuma', 'Lokichoggio'],
                'Turkana Central' => ['Kang\'atotha', 'Kalokol'],
                'Loima' => ['Loima', 'Lorugum'],
                'Turkana South' => ['Katilu', 'Lokichar'],
                'Turkana East' => ['Lokori/Kochodin', 'Katilia'],
            ],
            'West Pokot' => [
                'Kapenguria' => ['Kapenguria', 'Mnagei'],
                'Sigor' => ['Sook', 'Masol'],
                'Kacheliba' => ['Suam', 'Alale'],
                'Pokot South' => ['Batei', 'Lelan'],
            ],
            'Samburu' => [
                'Samburu West' => ['Lodokejek', 'Suguta Marmar'],
                'Samburu North' => ['Baragoi', 'Ndoto'],
                'Samburu East' => ['Wamba North', 'Wamba South'],
            ],
            'Trans Nzoia' => [
                'Kwanza' => ['Kwanza', 'Kapomboi'],
                'Endebess' => ['Endebess', 'Matumbei'],
                'Saboti' => ['Matisi', 'Tuwani'],
                'Kiminini' => ['Kiminini', 'Sirende'],
                'Cherangany' => ['Chepsiro/Kiptoror', 'Kaplamai'],
            ],
            'Uasin Gishu' => [
                'Soy' => ['Soy', 'Ziwa'],
                'Turbo' => ['Turbo', 'Kamagut'],
                'Moiben' => ['Moiben', 'Kapsowar'],
                'Ainabkoi' => ['Kaptagat', 'Kapsoya'],
                'Kapseret' => ['Simat/Kapseret', 'Kipkenyo'],
                'Kesses' => ['Racecourse', 'Tarakwa'],
            ],
            'Elgeyo-Marakwet' => [
                'Marakwet East' => ['Kapyego', 'Embobut/Embolot'],
                'Marakwet West' => ['Lelan', 'Kapsowar'],
                'Keiyo North' => ['Tambach', 'Kamariny'],
                'Keiyo South' => ['Chepkorio', 'Soy South'],
            ],
            'Nandi' => [
                'Tinderet' => ['Songhor/Soba', 'Tinderet'],
                'Aldai' => ['Kabwareng', 'Kaptumo/Kaboi'],
                'Nandi Hills' => ['Chepkunyuk', 'Kapchorua'],
                'Chesumei' => ['Lelmokwo/Ngechek', 'Kosirai'],
                'Emgwen' => ['Kapsabet', 'Chepterit'],
                'Mosop' => ['Ndalat', 'Kabiemit'],
            ],
            'Baringo' => [
                'Tiaty' => ['Kolowa', 'Tirioko'],
                'Baringo North' => ['Barwesa', 'Kabartonjo'],
                'Baringo Central' => ['Kabarnet', 'Kapropita'],
                'Baringo South' => ['Marigat', 'Mochongoi'],
                'Mogotio' => ['Emining', 'Mogotio'],
                'Eldama Ravine' => ['Lembus', 'Ravine'],
            ],
            'Laikipia' => [
                'Laikipia West' => ['Rumuruti', 'Salama'],
                'Laikipia East' => ['Nanyuki', 'Tigithi'],
                'Laikipia North' => ['Sosian', 'Mukogodo East'],
            ],
            'Nakuru' => [
                'Molo' => ['Molo', 'Elburgon'],
                'Njoro' => ['Njoro', 'Mau Narok'],
                'Naivasha' => ['Naivasha', 'Hell\'s Gate'],
                'Gilgil' => ['Gilgil', 'Elementaita'],
                'Kuresoi South' => ['Amalo', 'Kiptagich'],
                'Kuresoi North' => ['Keringet', 'Kamara'],
                'Subukia' => ['Subukia', 'Kabazi'],
                'Rongai' => ['Soin', 'Visoi'],
                'Bahati' => ['Bahati', 'Dundori'],
                'Nakuru Town West' => ['Kaptembwo', 'Barut'],
                'Nakuru Town East' => ['Biashara', 'Flamingo'],
            ],
            'Narok' => [
                'Kilgoris' => ['Kilgoris Central', 'Keyian'],
                'Emurua Dikirr' => ['Ilkerin', 'Ololmasani'],
                'Narok North' => ['Olokurto', 'Narok Town'],
                'Narok East' => ['Suswa', 'Keekonyokie'],
                'Narok South' => ['Loita', 'Mara'],
                'Narok West' => ['Ilmotiok', 'Melelo'],
            ],
            'Kajiado' => [
                'Kajiado North' => ['Ongata Rongai', 'Olkeri'],
                'Kajiado Central' => ['Kajiado Town', 'Dalalekutuk'],
                'Kajiado East' => ['Kitengela', 'Kenanie'],
                'Kajiado West' => ['Magadi', 'Keekonyokie'],
                'Kajiado South' => ['Loitokitok', 'Rombo'],
            ],
            'Kericho' => [
                'Kipkelion East' => ['Londiani', 'Chepseon'],
                'Kipkelion West' => ['Kunyak', 'Kamasian'],
                'Ainamoi' => ['Ainamoi', 'Kapsoit'],
                'Bureti' => ['Kipsonoi', 'Tegat'],
                'Belgut' => ['Kabianga', 'Cheptororiet/Seretut'],
                'Soin/Sigowet' => ['Sigowet', 'Kaplelartet'],
            ],
            'Bomet' => [
                'Sotik' => ['Rongena/Manaret', 'Kapletundo'],
                'Chepalungu' => ['Sigor', 'Nyangoina'],
                'Bomet East' => ['Merigi', 'Kembu'],
                'Bomet Central' => ['Ndaraweta', 'Singorwet'],
                'Konoin' => ['Mogogosiek', 'Embomos'],
            ],
            'Kakamega' => [
                'Lugari' => ['Lugari', 'Chekalini'],
                'Likuyani' => ['Likuyani', 'Kongoni'],
                'Malava' => ['West Kabras', 'Chemuche'],
                'Lurambi' => ['Shirere', 'Butsotso South'],
                'Navakholo' => ['Ingostse-Mathia', 'Shinoyi-Shikomari'],
                'Mumias West' => ['Mumias Central', 'Mumias North'],
                'Mumias East' => ['Lusheya/Lubinu', 'East Wanga'],
                'Matungu' => ['Kholera', 'Koyonzo'],
                'Butere' => ['Marama West', 'Shianda/Marenyo'],
                'Khwisero' => ['Kisa East', 'Kisa West'],
                'Shinyalu' => ['Isukha North', 'Murhanda'],
                'Ikolomani' => ['Idakho South', 'Idakho East'],
            ],
            'Vihiga' => [
                'Vihiga' => ['Lugaga/Wamuluma', 'South Maragoli'],
                'Sabatia' => ['Chavakali', 'Lyaduywa/Izava'],
                'Hamisi' => ['Shamakhokho', 'Tambua'],
                'Luanda' => ['Luanda Township', 'Mwibona'],
                'Emuhaya' => ['North East Bunyore', 'Central Bunyore'],
            ],
            'Bungoma' => [
                'Mt Elgon' => ['Kaptama', 'Kapsokwony'],
                'Sirisia' => ['Sirisia', 'Namwela'],
                'Kabuchai' => ['Kabuchai/Chwele', 'West Nalondo'],
                'Bumula' => ['Kimaeti', 'Siboti'],
                'Kanduyi' => ['Bukembe East', 'Bukembe West'],
                'Webuye East' => ['Mihuu', 'Ndivisi'],
                'Webuye West' => ['Sitikho', 'Matisi'],
                'Kimilili' => ['Kimilili', 'Maeni'],
                'Tongaren' => ['Tongaren', 'Milima'],
            ],
            'Busia' => [
                'Teso North' => ['Malaba Central', 'Angurai South'],
                'Teso South' => ['Chakol North', 'Chakol South'],
                'Nambale' => ['Bukhayo North/Walatsi', 'Bukhayo Central'],
                'Matayos' => ['Bukhayo West', 'Bukhayo East'],
                'Butula' => ['Marachi East', 'Marachi Central'],
                'Funyula' => ['Namboboto/Nambuku', 'Bwiri'],
                'Budalangi' => ['Bunyala North', 'Bunyala South'],
            ],
            'Siaya' => [
                'Ugenya' => ['West Ugenya', 'North Ugenya'],
                'Ugunja' => ['Sigomere', 'East Ugunja'],
                'Alego Usonga' => ['Siaya Township', 'Usonga'],
                'Gem' => ['West Gem', 'North Gem'],
                'Bondo' => ['Bondo Town', 'North Sakwa'],
                'Rarieda' => ['West Asembo', 'East Asembo'],
            ],
            'Kisumu' => [
                'Kisumu East' => ['Kajulu', 'Kolwa Central'],
                'Kisumu West' => ['North West Kisumu', 'South West Kisumu'],
                'Kisumu Central' => ['Market Milimani', 'Nyalenda A'],
                'Seme' => ['Central Seme', 'West Seme'],
                'Nyando' => ['Ahero', 'Awasi/Onjiko'],
                'Muhoroni' => ['Muhoroni/Koru', 'Masogo/Nyang\'oma'],
                'Nyakach' => ['South East Nyakach', 'Central Nyakach'],
            ],
            'Homa Bay' => [
                'Kasipul' => ['East Kamagak', 'West Kamagak'],
                'Kabondo Kasipul' => ['Kabondo East', 'Kabondo West'],
                'Karachuonyo' => ['Central', 'Kendu Bay Town'],
                'Rangwe' => ['Kagan', 'Kochia'],
                'Homa Bay Town' => ['Homa Bay Central', 'Homa Bay East'],
                'Ndhiwa' => ['Kanyikela', 'Kabuoch South/Pala'],
                'Mbita' => ['Lambwe', 'Rusinga Island'],
                'Suba' => ['Gwassi South', 'Gwassi North'],
            ],
            'Migori' => [
                'Rongo' => ['Central Kamagambo', 'North Kamagambo'],
                'Awendo' => ['Central Sakwa', 'South Sakwa'],
                'Suna East' => ['Suna Central', 'Suna Ragana'],
                'Suna West' => ['Wiga', 'Wasweta II'],
                'Uriri' => ['Central Kanyamkago', 'West Kanyamkago'],
                'Nyatike' => ['Kachieng', 'North Kadem'],
                'Kuria West' => ['Tagare', 'Nyamosense/Komosoko'],
                'Kuria East' => ['Ntimaru East', 'Ntimaru West'],
            ],
            'Kisii' => [
                'Bonchari' => ['Bomariba', 'Riana'],
                'South Mugirango' => ['Bogetenga', 'Tabaka'],
                'Bomachoge Borabu' => ['Boochi Tendere', 'Boochi Borabu'],
                'Bobasi' => ['Nyacheki', 'Sameta Mokwerero'],
                'Bomachoge Chache' => ['Majoge Basi', 'Boochi/Betian'],
                'Nyaribari Masaba' => ['Masimba', 'Gesusu'],
                'Nyaribari Chache' => ['Kegati', 'Kisii Central'],
                'Kitutu Chache North' => ['Sensi', 'Marani'],
                'Kitutu Chache South' => ['Nyakoe', 'Bogusero'],
            ],
            'Nyamira' => [
                'West Mugirango' => ['Bonyamatuta', 'Bosamaro'],
                'North Mugirango' => ['Ekerenyo', 'Itibo'],
                'Borabu' => ['Esise', 'Nyansiongo'],
                'Kitutu Masaba' => ['Manga', 'Kemera'],
            ],
            'Nairobi' => [
                'Westlands' => ['Kangemi', 'Mountain View'],
                'Dagoretti North' => ['Kilimani', 'Kawangware'],
                'Dagoretti South' => ['Riruta', 'Waithaka'],
                'Lang\'ata' => ['Karen', 'Nairobi West'],
                'Kibra' => ['Laini Saba', 'Lindi'],
                'Roysambu' => ['Zimmerman', 'Githurai 44'],
                'Kasarani' => ['Mwiki', 'Clay City'],
                'Ruaraka' => ['Baba Dogo', 'Utalii'],
                'Embakasi South' => ['Pipeline', 'Imara Daima'],
                'Embakasi North' => ['Kariobangi North', 'Dandora Area I'],
                'Embakasi Central' => ['Kayole South', 'Kayole North'],
                'Embakasi East' => ['Lower Savanna', 'Upper Savanna'],
                'Embakasi West' => ['Umoja I', 'Umoja II'],
                'Makadara' => ['Viwandani', 'Harambee'],
                'Kamukunji' => ['Eastleigh North', 'Pumwani'],
                'Starehe' => ['Ngara', 'Pangani'],
                'Mathare' => ['Hospital', 'Mabatini'],
            ],
        ];

        foreach ($counties as $homecountyName => $constituencies) {
            $county = Homecounty::create(['name' => $homecountyName]);

            foreach ($constituencies as $constituencyName => $subcounties) {
                $constituency = $county->constituencies()->create(['name' => $constituencyName]);

                
            }
        }
    }
}
